### ISSUE TITLE
Colors mishmash

### ISSUE THREAD

**Issue by AMBIENTE1** [jwd-ali/RingPieChart#1]
Hi,
thank you very much for your project! I would like to generate a pie chart and change the input data. When I do this, the colors start to display poorly. Try:
`
import UIKit
import RingPieChart

class ViewController: UIViewController {
    
    @IBOutlet weak private var percentageSegment: UISegmentedControl!
    @IBOutlet weak private var animationSegment: UISegmentedControl!
    private var cir :Circular!
    var aaa = [[Double]]()
    override func viewDidAppear(_ animated: Bool) {
     let bbb = [0.0,3.0,97.0]
        aaa.append(bbb)
        addToView()
    }
    
    private func addToView() {
        if (cir != nil)  {
            cir.removeFromSuperview()
        }
        
        print(aaa)
        
        let barva: [UIColor] = [.blue,.purple,.orange]
        cir = Circular(percentages: aaa[0], colors: barva)
        cir.animationType = AnimationStyle.init(rawValue: animationSegment.selectedSegmentIndex) ?? .animationFan
        cir.showPercentageStyle = PercentageStyle.init(rawValue: percentageSegment.selectedSegmentIndex) ?? .none
        cir.frame = CGRect(x: 50, y: 50, width: 300, height: 300)
        cir.lineWidth = 10
        cir.center = self.view.center
        
        self.view.addSubview(cir)
    }
    
    @IBAction private func animationStyles(_ sender: UISegmentedControl) {
        aaa = []
        let bbb = [97,3.0,0.0]
        aaa.append(bbb)
        addToView()
    }
    
    @IBAction private func percentagestyles(_ sender: UISegmentedControl) {
        
        aaa = []
        let bbb = [0.0,0.0,100.0]
        aaa.append(bbb)
        addToView()
    }
    
}

`

Do you have any idea where the mistake is?

**Comment by jwd-ali** [comment]
percentages are out of 100 ... like ... 20, 30, 50 .... sum of them should be 100 .... 0.0 will not show anything ... 3 will be very minimal... 97 takes all the color

**Comment by jwd-ali** [comment]
this framework does not support 0 ... so if something 0 .. remove that from array ...
